### ISSUE TITLE
run meets wrong and CUDA out of memory.

### ISSUE THREAD

**Issue by wintogo** [iworldtong/text_gcn.pytorch#1]
1、File "train.py", line 82, in <module>
    model_func = model_func.cuda()
2、 CUDA out of memory. Tried to allocate 28.27 GiB (GPU 0; 15.77 GiB total capacity; 47.02 MiB already allocated;  

why use so much cuda memeroy?

**Comment by iworldtong** [comment]
The graphs take up a lot of memory because of the huge dataset. 
If your computer has enough memory, use CPU to train may solve this problem. (Only two layers of the neural network will not be very slow)
